[OPTIONS]
; structure-based setup
psffile = setup/PROTEINNAME_clean_ca.psf
prmfile = setup/PROTEINNAME_clean_nscal1_fnn1_go_bt.xml

DNA_coding_file = S288C_coding_PROTEINNAME.fsa
start_growth_index = 0

md_steps = 10_000 # number of steps to check Z coordinate of C-terminal residue
dt = 0.015 ; time step in ps
scale_factor = 4331293 ; scale factor for time: real = scale_factor * simluation_time

; log parameters
nstxout = 5000 ; number of steps to write checkpoint = nstxout
nstlog = 5000 ; number of steps to print log

; control temperature coupling
tcoupl = yes
ref_t = 300 ; Kelvin- reference temperature
tau_t = 5 ;^-1

; output
outname = ctf_SETINDEX
;Use GPU/CPU
device = GPU
; If using GPU, use devide ID
gpu_id = 0
; If CPU is specified, then use ppn variable
ppn = 4
;Restart simulation
restart = no
minimize = no ;if not restart, then minimize will be loaded, otherwise, minimize=False
