[OPTIONS]
; structure-based setup
psffile = setup/PROTEINNAME_clean_ca.psf
prmfile = setup/PROTEINNAME_clean_nscal1_fnn1_go_bt.xml

; initial state can be chk file or cor file, from the ejection of ctf simulation
initial_state = ctf_SETINDEX_ejection.cor

md_steps = 100_000_000 # number of steps: 1.5 microsecond
dt = 0.015 ; time step in ps

; log parameters
nstxout = 5000 ; number of steps to write checkpoint = nstxout
nstlog = 5000 ; number of steps to print log

; control temperature coupling
tcoupl = yes
ref_t = 300 ; Kelvin- reference temperature
tau_t = 5 ;^-1

; output
outname = ptf_SETINDEX
;Use GPU/CPU
device = GPU
; If using GPU, use devide ID
gpu_id = 0
; If CPU is specified, then use ppn variable
ppn = 4
;Restart simulation
restart = no
minimize = no ;if not restart, then minimize will be loaded, otherwise, minimize=False
